set SERVEROUTPUT ON;
CREATE TABLE TRABAJADOR(SEGURO_SOCIAL INTEGER, 
                        NOMBRE VARCHAR2(25),
                        EDAD INTEGER,
                 CONSTRAINT PK_TRABAJADOR PRIMARY KEY(SEGURO_SOCIAL));
              
CREATE TABLE NOMINA(ID_NOMINA INTEGER, SEGURO_SOCIAL INTEGER, SUELDO_BASE FLOAT, HORAS_LABORADAS INTEGER, FECHA_PAGO DATE, 
CONSTRAINT PK_ID_NOMINA PRIMARY KEY (ID_NOMINA),
CONSTRAINT FK1_SEGURO_SOCIAL FOREIGN KEY (SEGURO_SOCIAL)
REFERENCES TRABAJADOR(SEGURO_SOCIAL));

CREATE SEQUENCE SEC_NOMINA
START WITH 1
INCREMENT BY 1
NOMAXVALUE;


CREATE OR REPLACE PROCEDURE GUARDAR_NOMINA(MY_ID_NOMINA OUT INTEGER, 
              MY_SEGURO_SOCIAL IN INTEGER, MY_SUELDO_BASE IN FLOAT, MY_HORAS_LABORADAS IN INTEGER, MY_FECHA_PAGO IN DATE)
              AS
              BEGIN
              SELECT SEC_NOMINA.NEXTVAL INTO MY_ID_NOMINA FROM DUAL;
              INSER INTO NOMINA(ID_NOMINA,SEGURO_SOCIAL,SUELDO_BASE,HORAS_LABORADAS,FECHA_PAGO)
              VALUES (MY_ID_NOMINA, MY_ID_SEGURO_SOCIAL, MY_SUELDO_BASE, MY_HORAS_LABORADAS);
              END;

CREATE OR REPLACE PROCEDURE GENERAR_TRABAJADOR(MY_SEGURO IN INTEGER, MY_NOMBRE IN VARCHAR2,MY_EDAD IN INTEGER, MY ID_NOMINA OUT INTEGER, MY_SUELDO_BASE IN FLOAT) AS
BEGIN
INSERT INTO TRABAJADOR VALUES(MY_SEGURO, MY_NOMBRE, MY_EDAD);
GUARDAR_NOMINA(MY_ID_NOMINA, MY_SEGURO, MY_SUELDO_BASE);
END;
/
