

CREATE TABLE TRABAJADOR(ID INTEGER PRIMARY KEY, NOMBRE VARCHAR2(20),SUELDO_BASE FLOAT);
CREATE TABLE RESPALDO(ID INTEGER PRIMARY KEY, NOMBRE VARCHAR2(20),SUELDO_BASE FLOAT);

CREATE OR REPLACE TRIGGER DIS_TRABAJADOR AFTER INSERT ON TRABAJADOR FOR EACH ROW 
BEGIN 
IF :NEW.TRABAJADOR <3 THEN
INSERT INTO HIJOMAYOR VALUES(:NEW.ID , :NEW.NOMBRE, :NEW.EDAD );
ELSE 
INSERT INTO HIJOMENOR VALUES(:NEW.ID, :NEW.NOMBRE, :NEW.EDAD);
END IF;
END;
/
